In [1]:
import cv2
import pandas as pd
import numpy as np

In [2]:
dataF = pd.read_csv('ARStats.csv')

,imageid,imageType,model,loss,classType,colorMode,clean,crop,resize,colorCorrect,...,activation,wloss,lr,learningDecay,earlyStop,epochsMax,epochs,voting,trainTime,accuracy
276,277,R,xception,focal,multiclass,LAB,False,False,True,False,...,relu,True,0.001,False,True,200,109,0,54.404642,50.0
277,278,R,xception,focal,multiclass,LAB,False,False,True,False,...,relu,True,0.001,False,True,200,130,0,62.805416,55.0
278,279,R,xception,focal,multiclass,LAB,False,False,True,False,...,relu,True,0.001,False,True,200,99,0,48.312397,61.0
279,280,R,xception,focal,multiclass,LAB,False,False,True,False,...,relu,True,0.001,False,True,200,200,0,96.157717,22.0
280,281,R,xception,focal,multiclass,LAB,False,False,True,False,...,relu,True,0.001,False,True,200,146,0,70.572277,66.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
371,372,NR,xception,focal,multiclass,RGB,True,True,True,False,...,siren,True,0.001,False,True,200,122,0,59.021330,88.0
372,373,NR,xception,focal,multiclass,RGB,True,True,True,False,...,siren,True,0.001,False,True,200,157,0,75.906697,88.0
373,374,NR,xception,focal,multiclass,RGB,True,True,True,False,...,siren,True,0.001,False,True,200,146,0,70.874762,83.0
374,375,NR,xception,focal,multiclass,RGB,True,True,True,False,...,siren,True,0.001,False,True,200,115,0,55.805686,77.0
375,376,NR,xception,focal,multiclass,RGB,True,True,True,False,...,siren,True,0.001,False,True,200,151,0,73.182604,88.0

In [ ]:
dataF.tail(21)

In [ ]:
data = dataF.to_numpy()

In [ ]:
#data[114:134]

In [ ]:
data20 = data[254:274]

In [ ]:
len(data20)

In [ ]:
accInc = []
accXc = []
timeIn = []
timeX = []
for i in range(len(data20)):
    if data20[i][2] == 'inception':
        accInc.append(data20[i][-1])
        timeIn.append(data20[i][-2])
    elif data20[i][2] == "xception":
        accXc.append(data20[i][-1])
        timeX.append(data20[i][-2])
    else:
        print(data[i][2])
print("NR Data")
print("Inception - %.2f%% (+/- %.2f%%) time - %d" % (np.mean(accInc), np.std(accInc), np.sum(timeIn)/60))  
print("Xception  - %.2f%% (+/- %.2f%%)" % (np.mean(accXc), np.std(accXc)))

In [ ]:
timeIn

[83.0, 83.0, 88.0, 88.0, 77.0, 77.0, 83.0, 83.0, 88.0, 83.0]

In [ ]:
rdata20 = data[114:134]
len(rdata20)

In [ ]:
accInc = []
accXc = []
timeIn = []
timeX = []
for i in range(len(rdata20)):
    if rdata20[i][2] == 'inception':
        accInc.append(rdata20[i][-1])
        timeIn.append(data[i][-2])
    elif rdata20[i][2] == "xception":
        accXc.append(rdata20[i][-1])
        timeX.append(data[i][-2])
print("R Data")
print("Inception - %.2f%% (+/- %.2f%%) time - %d" % (np.mean(accInc), np.std(accInc), np.sum(timeIn)/60))  
print("Xception  - %.2f%% (+/- %.2f%%) time - %d" % (np.mean(accXc), np.std(accXc), np.sum(timeIn)/60))

# For 5 fold CV

In [ ]:
cvData = []
cvIn =[]
cvX = []
timeIn = []
timeX = []
for i in range(len(data)):
    if data[i][1] == "CV-R":
        cvData.append(data)
        if data[i][2] == 'inception':
            cvIn.append(data[i][-1])
            timeIn.append(data[i][-2])
        elif data[i][2] == 'xception':
            cvX.append(data[i][-1])
            timeX.append(data[i][-2])

In [ ]:
print("%.2f%% (+/- %.2f%%)" % (np.mean(cvIn), np.std(cvIn)))

In [ ]:
print("%.2f%% (+/- %.2f%%)" % (np.mean(cvX), np.std(cvX)))

In [ ]:
np.sum(timeIn)/60

In [ ]:
np.sum(timeX)/60

In [ ]:
(99.78571799909696 * 90) /3600

In [ ]:
(100.15781449293718* 90) /3600

In [ ]:
a = {}
a["ball"] = 7
a.get("ball")

In [41]:
def cal_acc_mean_std(df):
    #print(df)
    print('mean : ', np.mean(df.iloc[:, -1]), '\n std  : ',np.std(df.iloc[:, -1]))

In [42]:
# lab
cal_acc_mean_std(dataF.iloc[276:276+10])

    imageid imageType     model   loss   classType colorMode  clean   crop  \
276     277         R  xception  focal  multiclass       LAB  False  False
277     278         R  xception  focal  multiclass       LAB  False  False
278     279         R  xception  focal  multiclass       LAB  False  False
279     280         R  xception  focal  multiclass       LAB  False  False
280     281         R  xception  focal  multiclass       LAB  False  False
281     282         R  xception  focal  multiclass       LAB  False  False
282     283         R  xception  focal  multiclass       LAB  False  False
283     284         R  xception  focal  multiclass       LAB  False  False
284     285         R  xception  focal  multiclass       LAB  False  False
285     286         R  xception  focal  multiclass       LAB  False  False

     resize  colorCorrect  ...  activation wloss     lr  learningDecay  \
276    True         False  ...        relu  True  0.001          False
277    True         False  ...        relu  True  0.001          False
278    True         False  ...        relu  True  0.001          False
279    True         False  ...        relu  True  0.001          False
280    True         False  ...        relu  True  0.001          False
281    True         False  ...        relu  True  0.001          False
282    True         False  ...        relu  True  0.001          False
283    True         False  ...        relu  True  0.001          False
284    True         False  ...        relu  True  0.001          False
285    True         False  ...        relu  True  0.001          False

     earlyStop  epochsMax  epochs  voting   trainTime   accuracy
276       True        200     109       0   54.404642       50.0
277       True        200     130       0   62.805416       55.0
278       True        200      99       0   48.312397       61.0
279       True        200     200       0   96.157717       22.0
280       True        200     146       0   70.572277       66.0
281       True        200     130       0   63.214343       55.0
282       True        200     100       0   48.903068       33.0
283       True        200     102       0   50.343419       33.0
284       True        200     120       0   58.288639       66.0
285       True        200     125       0   60.709364       50.0

[10 rows x 21 columns]
mean :  49.1
 std  :  14.272000560538105

In [26]:
lab_df = dataF.iloc[276:276+10]
lab_df

,imageid,imageType,model,loss,classType,colorMode,clean,crop,resize,colorCorrect,...,activation,wloss,lr,learningDecay,earlyStop,epochsMax,epochs,voting,trainTime,accuracy
276,277,R,xception,focal,multiclass,LAB,False,False,True,False,...,relu,True,0.001,False,True,200,109,0,54.404642,50.0
277,278,R,xception,focal,multiclass,LAB,False,False,True,False,...,relu,True,0.001,False,True,200,130,0,62.805416,55.0
278,279,R,xception,focal,multiclass,LAB,False,False,True,False,...,relu,True,0.001,False,True,200,99,0,48.312397,61.0
279,280,R,xception,focal,multiclass,LAB,False,False,True,False,...,relu,True,0.001,False,True,200,200,0,96.157717,22.0
280,281,R,xception,focal,multiclass,LAB,False,False,True,False,...,relu,True,0.001,False,True,200,146,0,70.572277,66.0
281,282,R,xception,focal,multiclass,LAB,False,False,True,False,...,relu,True,0.001,False,True,200,130,0,63.214343,55.0
282,283,R,xception,focal,multiclass,LAB,False,False,True,False,...,relu,True,0.001,False,True,200,100,0,48.903068,33.0
283,284,R,xception,focal,multiclass,LAB,False,False,True,False,...,relu,True,0.001,False,True,200,102,0,50.343419,33.0
284,285,R,xception,focal,multiclass,LAB,False,False,True,False,...,relu,True,0.001,False,True,200,120,0,58.288639,66.0
285,286,R,xception,focal,multiclass,LAB,False,False,True,False,...,relu,True,0.001,False,True,200,125,0,60.709364,50.0

In [29]:
print('lab average', sum(lab_df.iloc[:, -1])/len(lab_df.iloc[:, -1]))

lab average 49.1

In [31]:
rgb_df = dataF.iloc[286:286+10]
rgb_df

,imageid,imageType,model,loss,classType,colorMode,clean,crop,resize,colorCorrect,...,activation,wloss,lr,learningDecay,earlyStop,epochsMax,epochs,voting,trainTime,accuracy
286,287,R,xception,focal,multiclass,RGB,False,False,True,False,...,relu,True,0.001,False,True,200,101,0,50.770561,77.0
287,288,R,xception,focal,multiclass,RGB,False,False,True,False,...,relu,True,0.001,False,True,200,171,0,83.261364,77.0
288,289,R,xception,focal,multiclass,RGB,False,False,True,False,...,relu,True,0.001,False,True,200,149,0,72.454226,77.0
289,290,R,xception,focal,multiclass,RGB,False,False,True,False,...,relu,True,0.001,False,True,200,118,0,58.211717,66.0
290,291,R,xception,focal,multiclass,RGB,False,False,True,False,...,relu,True,0.001,False,True,200,107,0,52.721575,72.0
291,292,R,xception,focal,multiclass,RGB,False,False,True,False,...,relu,True,0.001,False,True,200,111,0,54.682552,72.0
292,293,R,xception,focal,multiclass,RGB,False,False,True,False,...,relu,True,0.001,False,True,200,192,0,94.125294,83.0
293,294,R,xception,focal,multiclass,RGB,False,False,True,False,...,relu,True,0.001,False,True,200,172,0,84.104162,77.0
294,295,R,xception,focal,multiclass,RGB,False,False,True,False,...,relu,True,0.001,False,True,200,163,0,79.584760,77.0
295,296,R,xception,focal,multiclass,RGB,False,False,True,False,...,relu,True,0.001,False,True,200,103,0,51.220479,77.0

In [40]:
print('rgb \n mean : ', np.mean(rgb_df.iloc[:, -1]), '\n std  : ',np.std(rgb_df.iloc[:, -1]))

rgb
 mean :  75.5
 std  :  4.295346318982906

In [33]:
rgb_aug_df = dataF.iloc[296:296+10]
rgb_aug_df

,imageid,imageType,model,loss,classType,colorMode,clean,crop,resize,colorCorrect,...,activation,wloss,lr,learningDecay,earlyStop,epochsMax,epochs,voting,trainTime,accuracy
296,297,R,xception,focal,multiclass,RGB,True,True,True,False,...,relu,True,0.001,False,True,200,200,0,96.092220,61.0
297,298,R,xception,focal,multiclass,RGB,True,True,True,False,...,relu,True,0.001,False,True,200,113,0,54.136529,83.0
298,299,R,xception,focal,multiclass,RGB,True,True,True,False,...,relu,True,0.001,False,True,200,124,0,59.505413,77.0
299,300,R,xception,focal,multiclass,RGB,True,True,True,False,...,relu,True,0.001,False,True,200,157,0,75.464479,77.0
300,301,R,xception,focal,multiclass,RGB,True,True,True,False,...,relu,True,0.001,False,True,200,108,0,51.882064,77.0
301,302,R,xception,focal,multiclass,RGB,True,True,True,False,...,relu,True,0.001,False,True,200,121,0,58.050848,83.0
302,303,R,xception,focal,multiclass,RGB,True,True,True,False,...,relu,True,0.001,False,True,200,117,0,56.393080,77.0
303,304,R,xception,focal,multiclass,RGB,True,True,True,False,...,relu,True,0.001,False,True,200,123,0,59.418241,83.0
304,305,R,xception,focal,multiclass,RGB,True,True,True,False,...,relu,True,0.001,False,True,200,147,0,70.291129,88.0
305,306,R,xception,focal,multiclass,RGB,True,True,True,False,...,relu,True,0.001,False,True,200,127,0,61.404934,83.0

In [34]:
print('rgb clean, crop average', sum(rgb_aug_df.iloc[:, -1])/len(rgb_aug_df.iloc[:, -1]))

rgb clean, crop average 78.9

In [35]:
bce_df = dataF.iloc[306:306+10]
bce_df

,imageid,imageType,model,loss,classType,colorMode,clean,crop,resize,colorCorrect,...,activation,wloss,lr,learningDecay,earlyStop,epochsMax,epochs,voting,trainTime,accuracy
306,307,R,xception,bce,multiclass,RGB,True,True,True,False,...,relu,True,0.001,False,True,200,137,0,66.791968,77.0
307,308,R,xception,bce,multiclass,RGB,True,True,True,False,...,relu,True,0.001,False,True,200,106,0,50.772232,83.0
308,309,R,xception,bce,multiclass,RGB,True,True,True,False,...,relu,True,0.001,False,True,200,111,0,53.685129,83.0
309,310,R,xception,bce,multiclass,RGB,True,True,True,False,...,relu,True,0.001,False,True,200,178,0,85.195008,83.0
310,311,R,xception,bce,multiclass,RGB,True,True,True,False,...,relu,True,0.001,False,True,200,113,0,54.922117,83.0
311,312,R,xception,bce,multiclass,RGB,True,True,True,False,...,relu,True,0.001,False,True,200,113,0,54.586115,83.0
312,313,R,xception,bce,multiclass,RGB,True,True,True,False,...,relu,True,0.001,False,True,200,102,0,49.829287,77.0
313,314,R,xception,bce,multiclass,RGB,True,True,True,False,...,relu,True,0.001,False,True,200,101,0,49.069764,83.0
314,315,R,xception,bce,multiclass,RGB,True,True,True,False,...,relu,True,0.001,False,True,200,120,0,57.780417,83.0
315,316,R,xception,bce,multiclass,RGB,True,True,True,False,...,relu,True,0.001,False,True,200,105,0,50.927515,83.0

In [36]:
print('bce average', sum(bce_df.iloc[:, -1])/len(bce_df.iloc[:, -1]))

bce average 81.8